# Generated by Django 3.1.7 on 2021-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='books',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='-', max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='-', max_length=100, verbose_name='Фамилия пользователя'),
        ),
    ]
