# Generated by Django 3.1.7 on 2021-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('books', '0004_auto_20210427_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='genres.Genre', verbose_name='Жанр фильма'),
        ),
    ]
