# Generated by Django 3.1.7 on 2021-04-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
