# Generated by Django 3.1.7 on 2021-05-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
